const box = document.getElementById('container');
box.style.backgroundColor = "yellow";
box.style.color = "blue";
box.style.margin ="20px";
box.style.padding ="10px";
box.style.fontSize = "18px";
box.style.fontWeight= "bold";
box.style.height ="200px";
box.style.width ="300px";